# ===========================================
# King Neon Docker Swarm - Development Stack
# ===========================================
# Deploy: docker stack deploy -c docker-stack.dev.yml king-neon-dev
# Remove: docker stack rm king-neon-dev
#
# NOTE: Uses different ports than prod to allow running both simultaneously
# Dev ports: web:3010, admin:3011, api:4010, cms:1347, minio:9010/9011

services:
  # ============================================
  # Infrastructure Services
  # ============================================
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-king_neon_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-king_neon_dev_secret}
      POSTGRES_DB: ${POSTGRES_DB:-king_neon_dev_db}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - king-neon-dev-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U king_neon_dev -d king_neon_dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data_dev:/data
    networks:
      - king-neon-dev-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-king_neon_minio_dev}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-king_neon_minio_dev_secret}
    volumes:
      - minio_data_dev:/data
    networks:
      - king-neon-dev-net
    ports:
      - "9010:9000" # API - dev port
      - "9011:9001" # Console - dev port
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # ============================================
  # Application Services
  # ============================================
  api:
    image: king-neon-api:dev
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-king_neon_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-king_neon_dev_secret}
      POSTGRES_DB: ${POSTGRES_DB:-king_neon_dev_db}
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-king_neon_minio_dev}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-king_neon_minio_dev_secret}
      MINIO_BUCKET: king-neon-dev
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-change-me}
    networks:
      - king-neon-dev-net
    ports:
      - "4010:4000" # API - dev port
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s

  web:
    image: king-neon-web:dev
    environment:
      NODE_ENV: development
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4010/api}
    networks:
      - king-neon-dev-net
    ports:
      - "3010:3000" # Web - dev port
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  admin:
    image: king-neon-admin:dev
    environment:
      NODE_ENV: development
      HOSTNAME: "0.0.0.0"
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4010/api}
    networks:
      - king-neon-dev-net
    ports:
      - "3011:3000" # Admin - dev port
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  king-neon-dev-net:
    driver: overlay
    attachable: true

volumes:
  postgres_data_dev:
  redis_data_dev:
  minio_data_dev:
