# ===========================================
# King Neon Docker Swarm - Production Stack
# ===========================================
# For single VPS with Cloudflare Tunnel
#
# Deploy: ./scripts/deploy-prod.sh
# Or manually: docker stack deploy -c docker-stack.prod.yml king-neon
#
# NOTE: Cloudflare Tunnel runs separately via docker-compose.tunnel.yml

services:
  # ============================================
  # Infrastructure Services
  # ============================================
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-king_neon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-king_neon_secret}
      POSTGRES_DB: ${POSTGRES_DB:-king_neon_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - king-neon-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U king_neon -d king_neon_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - king-neon-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-king_neon_minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-king_neon_minio_secret}
    volumes:
      - minio_data:/data
    networks:
      - king-neon-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # ============================================
  # Application Services
  # ============================================
  api:
    image: king-neon-api:latest
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-king_neon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-king_neon_secret}
      POSTGRES_DB: ${POSTGRES_DB:-king_neon_db}
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-king_neon_minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-king_neon_minio_secret}
      MINIO_USE_SSL: "false"
      MINIO_BUCKET: king-neon
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      CORS_ORIGINS: ${CORS_ORIGINS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    ports:
      - "4000:4000"
    networks:
      - king-neon-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  web:
    image: king-neon-web:latest
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
    ports:
      - "3000:3000"
    networks:
      - king-neon-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  admin:
    image: king-neon-admin:latest
    environment:
      NODE_ENV: production
      HOSTNAME: "0.0.0.0"
    ports:
      - "3001:3000"
    networks:
      - king-neon-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

# ============================================
# Networks
# ============================================
networks:
  king-neon-net:
    driver: overlay
    attachable: true

# ============================================
# Volumes
# ============================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local
